"""AUTO-GENERATED by build/bake_kb.py from docs/kb/*.md. Do not edit by hand."""
KB_TEXT = r'''# AI Document Inbox — turn bills into draft vouchers

*(AI features are on the higher plans and use your own Anthropic AI key — "BYOK". Add the
key in Settings → AI key first.)*

There are two AI screens:
- **AI Doc Reader** — quick, one-off: drop a single invoice and it fills a Sales/Purchase
  form for you to review and post.
- **Document Inbox** — a queue/workflow for many documents (below).

## Document Inbox — the flow
1. **Get documents in**, either way:
   - **Watch a folder** — set a folder in Settings; files dropped there appear in the queue.
   - **Pull from email** — set up an email inbox; the app polls it and pulls attachments
     (invoices, bills, statements).
2. **The queue** lists each document with a status: *Pending → Classified → Approved →
   Posted* (or *Rejected / Error*). Click a row to open it in the **3-pane review**: the
   document preview, its details, and the draft voucher — side by side.
3. **Process** — the AI reads the document once: it **classifies** it (purchase invoice,
   sales invoice, debit/credit note, bank statement, other) **and** drafts a voucher. If the
   classification is wrong, change it from the dropdown.
4. **Review & approve** — check the draft against the preview. Edit ledgers, amounts and
   narration as needed. Create a new ledger inline if the party isn't in your books yet.
5. **Post** — posts it to the Day Book and marks the document *Posted*. Nothing is posted
   silently — you approve every voucher.
6. **Process All** — runs extraction on all pending documents in the background; you still
   review and post each.

## Good to know
- The AI drafts the common 2-line voucher types (Payment, Receipt, Journal, Contra). Sales/
  Purchase with line items and notes are still entered through the normal form.
- Vouchers created from AI carry a source tag and a confidence score, so you can tell them
  apart later.
- If the inbox shows **Error**, the most common cause is the **AI key** — expired, wrong, or
  out of credit. Re-check it in Settings.

---

# Backup & restore

*(On the higher plans.)* Your whole company is a single file on your PC, so backing up is
simple and fast. Use the **Backup & Restore** screen.

## Create a backup
Click **Create Backup**. The app writes a timestamped copy of your company file to the
backups folder. The screen shows a history of backups (time, size).

## Restore a backup
Click **Restore**, pick a backup file, and confirm. The app safety-copies your current data
first, then restores from the chosen backup.

## Automatic reminder
If you haven't backed up in a while (default **7 days**, set in Settings), Accounts HQ
reminds you when you open the app. It keeps the most recent backups and trims the oldest.

## Best practice
- Back up before big operations (migration, bulk edits, reconciliation finalise).
- Copy a backup to a **pen-drive or cloud folder** now and then — the backup file is all you
  need to move your books to another PC.

## Moving to a new computer
Install Accounts HQ on the new PC, copy your company file (or a backup) across, and open it.
Your data is portable because it's just that one file.

---

# Getting started — install, create or open a company

## Install
Accounts HQ is a Windows desktop app. Download the installer (`Accounts HQ-Setup-x.x.x.exe`)
and run it. It installs locally — no internet is needed to use the app day to day.

## First launch — the company selector
When you open Accounts HQ, a **company selector** appears first.

**Open an existing company:** pick it from the dropdown (it lists every company you've
created) and click **Open**.

**Create a new company:**
1. Click to create a new company.
2. Fill in:
   - **Company Name** (required)
   - **GSTIN** (optional — if you enter it, the state code is filled in for you)
   - **State Code** (2-digit; defaults to 07/Delhi — set this correctly, it drives GST)
3. Click **Create & Open**. The app seeds a standard chart of accounts (Tally-style
   groups + ledgers, GST ledgers) and the current financial year.

**Create and bring over old books:** use **Create & Migrate from another system…** to
launch the migration wizard right after creating the company (see *Migrate from Tally /
Busy / Excel*).

## Where your data lives
Each company is a single file on your own PC:
`C:\Users\<you>\AppData\Local\Aiccounting\data\companies\<company>.db`

Your books never leave your machine unless you back them up or export. Because it's one
file per company, a backup is just a copy of that file (see *Backup & restore*).

## Financial year
A financial year (default **1 April – 31 March**) is created automatically. You can change
the FY start in **Settings → Financial year**.

## The main window
A sidebar on the left lists every screen (Post Voucher, Day Book, reports, reconciliation,
etc.). The screens you see depend on your plan — locked ones show an upgrade card. Click
the logo any time to return to the **Home** dashboard.

---

# GST on sales & purchases (and GST returns)

*(GST features are on the higher plans, India.)*

## How GST is split — the key rule
When you post a Sales or Purchase and choose a GST rate, Accounts HQ splits the tax based on
**your company's state code vs. the party's state code**:
- **Same state (intra-state):** tax splits into **CGST + SGST/UTGST** (half each), as
  separate ledger lines.
- **Different state (inter-state):** the full tax goes to **IGST** on one line.

So the split is only correct if **every customer/vendor ledger has the right 2-digit state
code**. If a party has no state code, the app assumes intra-state (your own state) — which can
silently mis-flag an inter-state invoice. **Fix: set the state code on every party ledger.**

## GST rates
Pick from the standard slabs: **0, 5, 12, 18, 28%**. The tax amount = base × rate.

## HSN / SAC
You can set an **HSN/SAC code** on item/sales ledgers. It feeds the **HSN Summary** report,
which groups sales by HSN code and rate for your return.

## GST reports / returns
On the higher plans you get GST report screens to prepare your filing:
- **GSTR-3B** — monthly summary
- **GSTR-1** — outward supplies
- **HSN Summary**
- **GSTR-2B reconciliation** — match your purchases against the portal's 2B
- **GST Returns** summary

Each computes the CGST/SGST/IGST figures from your posted vouchers and exports for the GST
portal. Accounts HQ **prepares** the numbers — you (or your CA) file them on the portal.

## Note
Accounts HQ records and computes GST from the rates and state codes you set. It is **not a
filing engine** and does not give tax advice — confirm rates and treatment with your CA.

---

# Migrate from Tally / Busy / Excel

*(Migration is on the higher plans.)* Bring an existing business onto Accounts HQ via the
**Migration** screen (or **Create & Migrate from another system…** in the company selector).

## What comes over
Migration imports your **chart of accounts (groups + ledgers) and their opening balances** —
the snapshot you start from. It does **not** import historical transactions; those stay in
your old system for reference. Accounts HQ is your book **going forward** from the opening
balances.

## Sources
- **Tally** — export from Tally and import the file
- **Busy**
- **Excel / CSV** — using the template (map your columns to ledger name, group, opening
  balance, etc.)
- **Zoho Books / QuickBooks** where offered

## Steps
1. Open the **Migration** wizard.
2. **Pick the source** and upload the file (or connect, for cloud sources).
3. **Map the columns** (for Excel) so the app knows which column is the ledger name, group,
   opening balance, etc.
4. **Preview** what will be imported — groups, ledgers, opening balances.
5. **Confirm** — the app seeds the ledgers and sets opening balances.

## Good to know
- Migration is meant for a **fresh/empty company** (before you've posted vouchers).
- After importing, check your **Trial Balance** — the opening balances should match your old
  system's closing position.
- The **Migration** screen keeps a history of past runs (source, file, counts, any errors).

---

# Posting vouchers

Go to **Post Voucher** in the sidebar (also a quick action on Home).

## The 8 voucher types
- **Payment** — money going out (bank/cash credited, party/expense debited)
- **Receipt** — money coming in (bank/cash debited, party/income credited)
- **Contra** — moving money between your own cash/bank accounts
- **Journal** — free-form, any number of debit/credit lines
- **Sales** — a sale (can auto-split GST)
- **Purchase** — a purchase (can auto-split GST)
- **Debit Note** / **Credit Note** — returns / allowances

## Posting a simple voucher (Payment / Receipt / Contra / Sales / Purchase)
1. Pick the **voucher type**.
2. Set the **date** (it can "stick" to the last-used date — see Settings).
3. Choose the **bank/cash** ledger (paid from / received into).
4. Choose the **party/expense/income** ledger and enter the **amount**.
5. For Sales/Purchase, pick the **GST rate** (0/5/12/18/28%) — the app splits CGST+SGST or
   IGST automatically (see *GST*). TDS is applied if the vendor ledger is set up for it
   (see *TDS*).
6. Add a **narration** and **reference** (e.g. cheque no.) if you like.
7. The live totals show **Dr**, **Cr** and the difference.
8. Click **Post**. The voucher must balance (Dr = Cr) or it won't post.

## Journal vouchers
Use **Journal** for entries that don't fit the simple forms. Add rows freely — each row is
a ledger with a debit or credit amount. Dr must equal Cr to post.

## Multi-party payment / receipt
Paying or receiving across several parties in one go? Use the **multi-party** option: one
bank/cash line and several party lines; the app totals them for you.

## Creating a ledger on the fly
If the party/ledger doesn't exist yet, create it from the ledger picker without leaving the
form. Set its group, opening balance, and (for parties) GSTIN/state code, and (for vendors)
TDS section if applicable.

## Editing or deleting a voucher
- Go to **Day Book**, select the voucher, and click **Edit** (or double-click it). Make
  changes and **Update**.
- **Delete** marks the voucher cancelled (soft delete — it stays in the audit trail).
- A voucher that has been **reconciled** (matched in bank/ledger reconciliation) is
  protected — you'll be warned; unreconcile it first if you really need to change it.
- A voucher whose date falls in a **locked period** can't be edited or posted (see
  *Settings, plans & period locks*).

## Bill-wise (against-reference) allocation
On a Payment/Receipt you can tag **which invoices** it settles: open **Bill Allocations**,
pick the party's outstanding bills and allocate amounts (one payment can settle several
bills). Track the result in the **Bill-wise Outstanding** report. *(Bill-wise is a higher-plan
feature.)*

---

# Bank & ledger reconciliation

*(Reconciliation is on the higher plans.)* Two screens: **Bank Reconciliation** (for a
bank/cash ledger) and **Ledger Reconciliation** (for any other ledger, e.g. a vendor
account). Both work the same way, in three steps.

## Step 1 — set up & import
1. Open **Bank Reconciliation** (or **Ledger Reconciliation**).
2. Pick the **ledger** to reconcile.
3. Set the **period** (From / To).
4. Select your **statement file** — CSV, Excel, PDF or OFX for bank; CSV/Excel for ledger.
   (PDF/image statements can be read by AI if you've added your own AI key.)
5. Click **Upload & Import**.

## Step 2 — review & match
You'll see three tabs:
- **Matched** — statement lines already paired with your vouchers (the app auto-matches by
  amount and date where it can).
- **Unmatched statement** — lines from the file with no voucher yet.
- **Unmatched book** — your vouchers with no statement line yet.

For each unmatched statement line you can:
- **Match** it to a book voucher (drag/click). One statement line can settle **several**
  vouchers (1-to-many) — e.g. a lump-sum bank debit covering three invoices.
- **Create Voucher** inline — pick the other ledger and amount, and it posts a
  Payment/Receipt and matches it.
- **Ignore** — mark it reconciled without posting (you may be asked for a comment, for the
  audit trail).

## Step 3 — finalise
The summary shows **statement balance, book balance, and the difference**. When the
difference is right, click **Finalise** to lock the reconciliation — matched vouchers are
marked reconciled.

## Good to know
- A **reconciled voucher is protected** from editing. If you must change it, undo the match
  first.
- Auto-match looks at amount + date (within a couple of days) and can suggest the usual
  counter-ledger based on your history.

---

# Reports — view, filter, drill-down, export

*(Most reports are on the higher plans; Day Book and Ledger Balances are available free.)*

## Always-free views
- **Day Book** — every voucher in a date range; filter by type or search the narration;
  edit/delete from here.
- **Ledger Balances** — the running balance of every ledger.

## Financial reports
- **Trial Balance** — opening, debits, credits and closing per ledger, as of a date.
- **Profit & Loss** — income vs. expenses and net profit.
- **Balance Sheet** — assets vs. liabilities.
- **Cash Book / Bank Book** — cash and bank movements with a running balance.
- **Ledger Account** — every voucher for one ledger (the drill-down target).
- **Receipts & Payments** — summary across ledgers.
- **Receivables / Payables Aging** — who owes you / whom you owe, in buckets (0–30, 30–60,
  60+ days).
- **Cash-Flow Planning** — a forward cash view based on aging *(higher plan)*.
- **Bill-wise Outstanding** — which bills are settled / outstanding *(higher plan)*.
- GST and TDS reports — see the *GST* and *TDS* articles.

## Using a report
1. Set the **From/To** dates (or the single **As of** date).
2. **Filter rows…** — type to narrow the table instantly.
3. **Drill down** — click an account name in Trial Balance / P&L / Balance Sheet to jump to
   its **Ledger Account**; double-click a line in a register to open the **voucher** itself.
4. **Export** — **⬇ Excel**, **⬇ PDF**, or **Print**. (Email a report where offered.)

## Tip
Reports read your posted vouchers live — post or fix an entry and just **Refresh** the
report to see it update.

---

# Settings, plans & period locks

## Settings
Open **Settings** from the sidebar. Common preferences:
- **Debit/Credit label style** — *Natural*, *Traditional*, or *Accounting*. Changes the
  Dr/Cr wording across the whole app.
- **Default voucher date** — *Today* or *Last-used* (the "sticky date").
- **After-post confirmation** — show/hide the "voucher posted" toast.
- **Financial year start** — default 1 April (India).
- **Company tax IDs** — GSTIN and TAN.
- **AI / Anthropic key** — your own key, required for the AI Document Inbox / Reader (BYOK).
- **Backup reminder interval** — how often to nudge you to back up.
- **Bank reconciliation: ask for a comment when ignoring a line** — for the audit trail.

## Plans & activation (License & Plan screen)
Accounts HQ runs on a plan. Roughly:
- **Free** — day-to-day entry and basic views.
- **Standard** — full financial reports, bank/ledger reconciliation, backup, migration.
- **Pro / Premium** — GST & TDS reports, AI Document Inbox/Reader, bill-wise, cash-flow
  planning, more users.

*(See the website Pricing page for the current plan limits and prices.)*

**To activate:** open **License & Plan**, paste your licence key, and save. Locked features
show an **Upgrade** card until your plan includes them. After changing plans you may need to
restart the app to unlock features.

**Offline:** the licence is cached on your PC and keeps working offline for a grace period;
it re-checks with the server in the background when you're online.

**Transactions counter:** your plan includes a number of transactions; each posted voucher
counts toward it.

## Period locks
Open **Period Locks** to **lock a date range** so no one can post, edit or cancel vouchers in
it — useful after you've closed and filed a period. Locked-period entries are blocked at the
moment you try to post or edit. Remove the lock to make changes again.

---

# TDS on payments

*(TDS features are on the higher plans, India.)*

## Setting up a vendor for TDS
TDS is driven by the **vendor's ledger settings**. Open the vendor ledger and set:
- **TDS applicable** = yes
- the **TDS section** (e.g. 194C contractors, 194I rent, 194J professional fees, 194H
  commission, etc.)
- the **TDS rate** for that section

Once set, when you make a Payment to that vendor, Accounts HQ deducts TDS automatically and
posts it to the **TDS Payable** ledger.

## Thresholds
Each section has a threshold below which TDS doesn't apply. The app applies TDS when the
amount crosses the section's threshold — so a payment just under the threshold won't deduct.
Keep this in mind if you expect a deduction and don't see one.

> Exact section rates and thresholds change with the Finance Act. Accounts HQ applies the
> rate set on the ledger — **confirm current rates/thresholds with your CA**. The app does
> not give tax advice.

## Reports
- **TDS Reports** and **TDS Register** show deductions by section and party, so you can
  reconcile what you deducted against what you paid/filed.

## Common question
**"I expected TDS but it didn't deduct."** Check three things: (1) the vendor ledger has TDS
applicable + a section + a rate; (2) the payment amount is **above** the section threshold;
(3) you're on a plan that includes TDS.

---

# Troubleshooting & common questions

## "It's asking for my licence key again after I updated."
Your data is safe — books live in `…\AppData\Local\Aiccounting\` and aren't touched by an
update. Re-open **License & Plan** and paste your key. If it keeps dropping, contact
`info@ai-consultants.in` with your key. *(Known issue under investigation.)*

## "My voucher won't post."
The most common reasons:
- **Dr ≠ Cr** — the debits and credits must balance. Check the live totals on the form.
- **Locked period** — the voucher date is inside a locked range (see Period Locks).
- A required ledger/amount is missing.

## "GST split as CGST/SGST but it was an inter-state sale (or vice-versa)."
GST is decided by **state codes**: same state → CGST+SGST, different state → IGST. Make sure
**your company state code** and the **party ledger's state code** are both correct. A party
with no state code is treated as intra-state. Fix the ledger's state code and re-post.

## "I expected TDS to be deducted but it wasn't."
Check: (1) the vendor ledger has **TDS applicable + section + rate**; (2) the payment is
**above** that section's threshold; (3) your plan includes TDS. See *TDS*.

## "I can't edit this voucher."
It's probably **reconciled** (matched in bank/ledger reconciliation) and therefore protected,
or its date is in a **locked period**. Undo the reconciliation match, or unlock the period,
then edit.

## "The AI Document Inbox shows an error."
Almost always the **AI key**: it's missing, wrong, expired, or out of credit. AI features are
"bring your own key" — set/replace it in **Settings → AI key**. AI features also need a Pro/
Premium plan.

## "A report looks out of date."
Reports read posted vouchers live — click **Refresh** after posting or fixing an entry.

## "Where is my data / how do I move to another PC?"
Each company is one file: `…\AppData\Local\Aiccounting\data\companies\<company>.db`. Back it
up (Backup & Restore), copy the backup to the new PC, install Accounts HQ there, and restore/
open it. Your data never leaves your machine unless you move it.

## "Can Accounts HQ file my GST/TDS returns?"
No. It **prepares** the figures and exports them for the portal; you or your CA file. It
records and computes — it isn't a filing/compliance engine and doesn't give tax advice.

## Still stuck?
Email **info@ai-consultants.in** with what you were doing and any error text.'''
