"""AUTO-GENERATED by build/bake_kb.py from docs/kb/*.md. Do not edit by hand."""
KB_TEXT = r'''# AI Documents Inbox — turn bills, invoices and statements into entries

*(AI document reading is on the higher plans. It runs on either your Accounts HQ
wallet credits or your own Anthropic AI key — whichever you chose in Settings → AI.
Bank and ledger statements in a structured file are read locally, with no AI and no cost.)*

The **AI Documents Inbox** is one screen that collects your documents and turns them
into draft vouchers — or feeds statements into reconciliation. It replaces the older
separate "AI Doc Reader" and "Document Inbox".

## Getting documents in
- **Drop or add files** — drag a PDF, photo or scan onto the inbox, or use *Add Files*.
- **Scan a folder** — point the inbox at a folder; anything dropped there appears in the queue.
- **Connect email** — the app pulls invoices, bills and statements from a mailbox you set up.

## Processing a document
1. **Pick the document** on the left — its preview shows in the middle.
2. **Choose the type** (optional). The dropdown defaults to **"Auto — let AI decide"**. If you
   already know it (e.g. *Purchase Invoice*), pick it and the AI skips the guess step. Pick
   **Bank statement** or **Ledger statement** and it is read **locally, with no AI**.
3. **Process with AI** processes that one document now (it jumps the queue); **Process All**
   runs the whole inbox. The AI reads the document, drafts the voucher(s) and shows a
   **confidence score**.
4. **Review & approve** — check the draft against the preview, fix any field, add a ledger
   inline if the party is new, then **Approve & Post**. Nothing posts silently.
5. **Auto-post** (optional, off by default) — tick it and the confident, complete documents
   post on their own without review. The recommended way is still AI-assisted review.

## Bank & ledger statements
A bank or ledger statement isn't a voucher — it belongs in **Reconciliation**. Pick the
*Bank statement* or *Ledger statement* type and process it: it is read locally (CSV / Excel /
OFX), tells you how many transactions it found, and gives a **Send to Reconciliation** button
that opens the right reconciliation screen with the file ready to import. Importing dedups by
file, so it never disturbs a reconciliation already in progress.

## Good to know
- Documents created from AI carry a source tag and a confidence score, so you can tell them apart later.
- A photo or scanned PDF is read by AI (an image has no text to read locally). A clean CSV / Excel /
  OFX statement is read locally with no AI cost.
- If the inbox shows **Error** on an AI document, the usual cause is billing — your wallet is out of
  credit, or your own AI key is expired/wrong. The message says which; fix it in Settings → AI.

---

# Backup & restore

*(On the higher plans.)* Your whole company is a single file on your PC, so backing up is
simple and fast. Use the **Backup & Restore** screen.

## Create a backup
Click **Create Backup**. The app writes a timestamped copy of your company file to the
backups folder. The screen shows a history of backups (time, size).

## Restore a backup
Click **Restore**, pick a backup file, and confirm. The app safety-copies your current data
first, then restores from the chosen backup.

## Automatic reminder
If you haven't backed up in a while (default **7 days**, set in Settings), Accounts HQ
reminds you when you open the app. It keeps the most recent backups and trims the oldest.

## Best practice
- Back up before big operations (migration, bulk edits, reconciliation finalise).
- Copy a backup to a **pen-drive or cloud folder** now and then — the backup file is all you
  need to move your books to another PC.

## Moving to a new computer
Install Accounts HQ on the new PC, copy your company file (or a backup) across, and open it.
Your data is portable because it's just that one file.

---

# Getting started — install, create or open a company

## Install
Accounts HQ is a Windows desktop app. Download the installer (`Accounts HQ-Setup-x.x.x.exe`)
and run it. It installs locally — no internet is needed to use the app day to day.

## First launch — the company selector
When you open Accounts HQ, a **company selector** appears first.

**Open an existing company:** pick it from the dropdown (it lists every company you've
created) and click **Open**.

**Create a new company:**
1. Click to create a new company.
2. Fill in:
   - **Company Name** (required)
   - **GSTIN** (optional — if you enter it, the state code is filled in for you)
   - **State Code** (2-digit; defaults to 07/Delhi — set this correctly, it drives GST)
3. Click **Create & Open**. The app seeds a standard chart of accounts (Tally-style
   groups + ledgers, GST ledgers) and the current financial year.

**Create and bring over old books:** use **Create & Migrate from another system…** to
launch the migration wizard right after creating the company (see *Migrate from Tally /
Busy / Excel*).

## Where your data lives
Each company is a single file on your own PC:
`C:\Users\<you>\AppData\Local\Aiccounting\data\companies\<company>.db`

Your books never leave your machine unless you back them up or export. Because it's one
file per company, a backup is just a copy of that file (see *Backup & restore*).

## Financial year
A financial year (default **1 April – 31 March**) is created automatically. You can change
the FY start in **Settings → Financial year**.

## The main window
A sidebar on the left lists every screen (Post Voucher, Day Book, reports, reconciliation,
etc.). The screens you see depend on your plan — locked ones show an upgrade card. Click
the logo any time to return to the **Home** dashboard.

---

# GST on sales & purchases (and GST returns)

*(GST features are on the higher plans, India.)*

## How GST is split — the key rule
When you post a Sales or Purchase and choose a GST rate, Accounts HQ splits the tax based on
**your company's state code vs. the party's state code**:
- **Same state (intra-state):** tax splits into **CGST + SGST/UTGST** (half each), as
  separate ledger lines.
- **Different state (inter-state):** the full tax goes to **IGST** on one line.

So the split is only correct if **every customer/vendor ledger has the right 2-digit state
code**. If a party has no state code, the app assumes intra-state (your own state) — which can
silently mis-flag an inter-state invoice. **Fix: set the state code on every party ledger.**

## GST rates
Pick from the standard slabs: **0, 5, 12, 18, 28%**. The tax amount = base × rate.

## HSN / SAC
You can set an **HSN/SAC code** on item/sales ledgers. It feeds the **HSN Summary** report,
which groups sales by HSN code and rate for your return.

## GST reports / returns
On the higher plans you get GST report screens to prepare your filing:
- **GSTR-3B** — monthly summary
- **GSTR-1** — outward supplies
- **HSN Summary**
- **GSTR-2B reconciliation** — match your purchases against the portal's 2B
- **GST Returns** summary

Each computes the CGST/SGST/IGST figures from your posted vouchers and exports for the GST
portal. Accounts HQ **prepares** the numbers — you (or your CA) file them on the portal.

## Note
Accounts HQ records and computes GST from the rates and state codes you set. It is **not a
filing engine** and does not give tax advice — confirm rates and treatment with your CA.

---

# Migrate from Tally / Busy / Excel

*(Migration is on the higher plans.)* Bring an existing business onto Accounts HQ via the
**Migration** screen (or **Create & Migrate from another system…** in the company selector).

## What comes over
Migration imports your **chart of accounts (groups + ledgers) and their opening balances** —
the snapshot you start from. It does **not** import historical transactions; those stay in
your old system for reference. Accounts HQ is your book **going forward** from the opening
balances.

## Sources
- **Tally** — export from Tally and import the file
- **Busy**
- **Excel / CSV** — using the template (map your columns to ledger name, group, opening
  balance, etc.)
- **Zoho Books / QuickBooks** where offered

## Steps
1. Open the **Migration** wizard.
2. **Pick the source** and upload the file (or connect, for cloud sources).
3. **Map the columns** (for Excel) so the app knows which column is the ledger name, group,
   opening balance, etc.
4. **Preview** what will be imported — groups, ledgers, opening balances.
5. **Confirm** — the app seeds the ledgers and sets opening balances.

## Good to know
- Migration is meant for a **fresh/empty company** (before you've posted vouchers).
- After importing, check your **Trial Balance** — the opening balances should match your old
  system's closing position.
- The **Migration** screen keeps a history of past runs (source, file, counts, any errors).

---

# Posting vouchers

Go to **Post Voucher** in the sidebar (also a quick action on Home).

## The 8 voucher types
- **Payment** — money going out (bank/cash credited, party/expense debited)
- **Receipt** — money coming in (bank/cash debited, party/income credited)
- **Contra** — moving money between your own cash/bank accounts
- **Journal** — free-form, any number of debit/credit lines
- **Sales** — a sale (can auto-split GST)
- **Purchase** — a purchase (can auto-split GST)
- **Debit Note** / **Credit Note** — returns / allowances

## Posting a simple voucher (Payment / Receipt / Contra / Sales / Purchase)
1. Pick the **voucher type**.
2. Set the **date** (it can "stick" to the last-used date — see Settings).
3. Choose the **bank/cash** ledger (paid from / received into).
4. Choose the **party/expense/income** ledger and enter the **amount**.
5. For Sales/Purchase, pick the **GST rate** (0/5/12/18/28%) — the app splits CGST+SGST or
   IGST automatically (see *GST*). TDS is applied if the vendor ledger is set up for it
   (see *TDS*).
6. Add a **narration** and **reference** (e.g. cheque no.) if you like.
7. The live totals show **Dr**, **Cr** and the difference.
8. Click **Post**. The voucher must balance (Dr = Cr) or it won't post.

## Journal vouchers
Use **Journal** for entries that don't fit the simple forms. Add rows freely — each row is
a ledger with a debit or credit amount. Dr must equal Cr to post.

## Multi-party payment / receipt
Paying or receiving across several parties in one go? Use the **multi-party** option: one
bank/cash line and several party lines; the app totals them for you.

## Creating a ledger on the fly
If the party/ledger doesn't exist yet, create it from the ledger picker without leaving the
form. Set its group, opening balance, and (for parties) GSTIN/state code, and (for vendors)
TDS section if applicable.

## Editing or deleting a voucher
- Go to **Day Book**, select the voucher, and click **Edit** (or double-click it). Make
  changes and **Update**.
- **Delete** marks the voucher cancelled (soft delete — it stays in the audit trail).
- A voucher that has been **reconciled** (matched in bank/ledger reconciliation) is
  protected — you'll be warned; unreconcile it first if you really need to change it.
- A voucher whose date falls in a **locked period** can't be edited or posted (see
  *Settings, plans & period locks*).

## Bill-wise (against-reference) allocation
On a Payment/Receipt you can tag **which invoices** it settles: open **Bill Allocations**,
pick the party's outstanding bills and allocate amounts (one payment can settle several
bills). Track the result in the **Bill-wise Outstanding** report. *(Bill-wise is a higher-plan
feature.)*

---

# Bank & ledger reconciliation

*(Reconciliation is on the higher plans.)* Two screens: **Bank Reconciliation** (for a
bank/cash ledger) and **Ledger Reconciliation** (for any other ledger, e.g. a vendor
account). Both work the same way, in three steps.

## Step 1 — set up & import
1. Open **Bank Reconciliation** (or **Ledger Reconciliation**).
2. Pick the **ledger** to reconcile.
3. Set the **period** (From / To).
4. Select your **statement file** — CSV, Excel, PDF or OFX for bank; CSV/Excel for ledger.
   (PDF/image statements can be read by AI if you've added your own AI key.)
5. Click **Upload & Import**.

## Step 2 — review & match
You'll see three tabs:
- **Matched** — statement lines already paired with your vouchers (the app auto-matches by
  amount and date where it can).
- **Unmatched statement** — lines from the file with no voucher yet.
- **Unmatched book** — your vouchers with no statement line yet.

For each unmatched statement line you can:
- **Match** it to a book voucher (drag/click). One statement line can settle **several**
  vouchers (1-to-many) — e.g. a lump-sum bank debit covering three invoices.
- **Create Voucher** inline — pick the other ledger and amount, and it posts a
  Payment/Receipt and matches it.
- **Ignore** — mark it reconciled without posting (you may be asked for a comment, for the
  audit trail).

## Step 3 — finalise
The summary shows **statement balance, book balance, and the difference**. When the
difference is right, click **Finalise** to lock the reconciliation — matched vouchers are
marked reconciled.

## From the AI Documents Inbox
You can send a statement straight here: in the **AI Documents Inbox**, process it as a
*Bank statement* or *Ledger statement* (read locally, no AI), then click **Send to
Reconciliation**. It opens this screen with the file pre-loaded — you just confirm the
ledger and period and import. Importing dedups by file, so it won't disturb a
reconciliation already underway.

## Good to know
- A **reconciled voucher is protected** from editing. If you must change it, undo the match
  first.
- Auto-match looks at amount + date (within a couple of days) and can suggest the usual
  counter-ledger based on your history.

---

# Reports — view, filter, drill-down, export

*(Most reports are on the higher plans; Day Book and Ledger Balances are available free.)*

## Always-free views
- **Day Book** — every voucher in a date range; filter by type or search the narration;
  edit/delete from here.
- **Ledger Balances** — the running balance of every ledger.

## Financial reports
- **Trial Balance** — opening, debits, credits and closing per ledger, as of a date.
- **Profit & Loss** — income vs. expenses and net profit.
- **Balance Sheet** — assets vs. liabilities.
- **Cash Book / Bank Book** — cash and bank movements with a running balance.
- **Ledger Account** — every voucher for one ledger (the drill-down target).
- **Receipts & Payments** — summary across ledgers.
- **Receivables / Payables Aging** — who owes you / whom you owe, in buckets (0–30, 30–60,
  60+ days).
- **Cash-Flow Planning** — a forward cash view based on aging *(higher plan)*.
- **Bill-wise Outstanding** — which bills are settled / outstanding *(higher plan)*.
- GST and TDS reports — see the *GST* and *TDS* articles.

## Using a report
1. Set the **From/To** dates (or the single **As of** date).
2. **Filter rows…** — type to narrow the table instantly.
3. **Drill down** — click an account name in Trial Balance / P&L / Balance Sheet to jump to
   its **Ledger Account**; double-click a line in a register to open the **voucher** itself.
4. **Export** — **⬇ Excel**, **⬇ PDF**, or **Print**. (Email a report where offered.)

## Tip
Reports read your posted vouchers live — post or fix an entry and just **Refresh** the
report to see it update.

---

# RWA HQ — Broadcasts, joining residents and cloud sync

## Broadcasts / official channel
Broadcasts let the society — or an approved vendor — send a message to everyone through an official channel, with consent and billing handled. This is separate from resident-to-resident chat.

## Joining residents
Invite residents with a **join link** and your society's **HQ-ID**; a light **soft-KYC** step confirms who they are.

## Cloud sync
The desktop app is the source of truth. Resident-facing data (units, members, notices, dues) syncs to the cloud so the mobile app and resident portal stay current. Your accounting books stay on your PC.

---

# RWA HQ — Maintenance billing, dues and collection

Raise maintenance bills against units, record receipts as residents pay, and track who is in arrears.

Residents can pay through your society's **UPI ID** (set in Society Settings) — the money goes **straight to the society's account**; RWA HQ never holds or routes it. Processing a resident payment is free.

Because billing is backed by full accounting, you get proper ledgers, aging and statements for dues — not just a list. See the RWA Reports and the Accounts HQ reports articles.

---

# RWA HQ — Getting started (install, create society, Quick Setup)

## Install
Download RWA HQ from the website and run the installer. It's a Windows desktop app.

## Create your society
On first launch, create your society. A **Quick Setup wizard** then runs automatically.

On the **"Your society"** page set:
- Society name
- State code (2-digit, drives GST) and GSTIN if you have one
- The books year (financial year)
- **Whether your units are Flats or Plots** — this labels units throughout the app (the "Flats" screen becomes "Plots", etc.). Set it before adding units.

You can re-run the wizard any time from the **⚙ Setup** button in the status bar, or the tile menu under **Settings → Quick Setup**. It re-opens after a plan upgrade to set up newly unlocked features.

## Finding your way around
Two navigation styles (choose in Settings): a **sidebar** list on the left, or a **tile menu** opened with the **☰ Menu** button. The status bar always shows Menu, the sidebar toggle, the ⚙ Setup button, and your AI Credits balance.

---

# RWA HQ — Notices and complaints

## Notices
Post announcements from the desktop app. They appear in the resident mobile app and can also be sent over WhatsApp.

## Complaints
Residents raise issues from the app. The office tracks each complaint and closes it when resolved.

(Resident-to-resident chat happens only inside the mobile app; the manager stays in Notices and Complaints.)

---

# RWA HQ — What it is and how it's used

RWA HQ runs a residents' welfare association or apartment/plot society. It has two parts:

- **The desktop app** (Windows) — the office/manager side: members and units, maintenance billing and dues, notices, complaints, visitor passes, broadcasts, and full society accounting. Your data lives on your own PC.
- **The resident mobile app** (free, iOS/Android) — what residents use: notices, complaints, chat with neighbours, visitor passes, and paying their dues.

Resident-facing data syncs securely to the cloud so the mobile app and resident portal work; the desktop app is the source of truth.

RWA HQ **records and reports** — it is not a statutory filing or compliance engine. For tax questions, defer to your CA.

RWA HQ is built on the same accounting engine as Accounts HQ, so all the accounting screens (vouchers, GST, reports, reconciliation, backup) work the same way.

---

# RWA HQ — The resident mobile app

Residents install the free **RWA HQ** app (iOS/Android). It gives them:
- Notices and complaints
- **Chat** — one-to-one and group chats with neighbours, without sharing phone numbers, plus calls
- **Visitor passes** from their phone
- Their **maintenance dues** with UPI payment

The app **updates itself** — residents don't reinstall to get new features. New residents join via a society **join link** and the society's **HQ-ID**, with a light soft-KYC step to confirm identity.

---

# RWA HQ — Units (Flats/Plots) and members

## Flats / Plots
The Flats (or Plots) screen is your register of units. Each unit has an owner/resident and its own maintenance ledger, so its dues and receipts feed straight into the accounts. The screen's name follows the Flats/Plots choice made in setup.

## Members
The Members screen lists owners and residents with their contact details and their access to the resident mobile app. Keep it current so notices, bills and app access reach the right people.

---

# RWA HQ — Visitor passes

A visitor pass is created with a code — either by a resident from the mobile app, or by the office. The gate verifies the code when the visitor arrives; the resident gets a WhatsApp confirmation, and the office keeps a copy.

There is no manager-approval step in the middle — it's designed to be quick at the gate, like other society gate apps.

---

# Settings, plans & period locks

## Settings
Open **Settings** from the sidebar. Common preferences:
- **Debit/Credit label style** — *Natural*, *Traditional*, or *Accounting*. Changes the
  Dr/Cr wording across the whole app.
- **Default voucher date** — *Today* or *Last-used* (the "sticky date").
- **After-post confirmation** — show/hide the "voucher posted" toast.
- **Financial year start** — default 1 April (India).
- **Company tax IDs** — GSTIN and TAN.
- **AI / Anthropic key** — your own key, required for the AI Document Inbox / Reader (BYOK).
- **Backup reminder interval** — how often to nudge you to back up.
- **Bank reconciliation: ask for a comment when ignoring a line** — for the audit trail.

## Plans & activation (License & Plan screen)
Accounts HQ runs on a plan. Roughly:
- **Free** — day-to-day entry and basic views.
- **Standard** — full financial reports, bank/ledger reconciliation, backup, migration.
- **Pro / Premium** — GST & TDS reports, AI Document Inbox/Reader, bill-wise, cash-flow
  planning, more users.

*(See the website Pricing page for the current plan limits and prices.)*

**To activate:** open **License & Plan**, paste your licence key, and save. Locked features
show an **Upgrade** card until your plan includes them. After changing plans you may need to
restart the app to unlock features.

**Offline:** the licence is cached on your PC and keeps working offline for a grace period;
it re-checks with the server in the background when you're online.

**Transactions counter:** your plan includes a number of transactions; each posted voucher
counts toward it.

## Period locks
Open **Period Locks** to **lock a date range** so no one can post, edit or cancel vouchers in
it — useful after you've closed and filed a period. Locked-period entries are blocked at the
moment you try to post or edit. Remove the lock to make changes again.

---

# TDS on payments

*(TDS features are on the higher plans, India.)*

## Setting up a vendor for TDS
TDS is driven by the **vendor's ledger settings**. Open the vendor ledger and set:
- **TDS applicable** = yes
- the **TDS section** (e.g. 194C contractors, 194I rent, 194J professional fees, 194H
  commission, etc.)
- the **TDS rate** for that section

Once set, when you make a Payment to that vendor, Accounts HQ deducts TDS automatically and
posts it to the **TDS Payable** ledger.

## Thresholds
Each section has a threshold below which TDS doesn't apply. The app applies TDS when the
amount crosses the section's threshold — so a payment just under the threshold won't deduct.
Keep this in mind if you expect a deduction and don't see one.

> Exact section rates and thresholds change with the Finance Act. Accounts HQ applies the
> rate set on the ledger — **confirm current rates/thresholds with your CA**. The app does
> not give tax advice.

## Reports
- **TDS Reports** and **TDS Register** show deductions by section and party, so you can
  reconcile what you deducted against what you paid/filed.

## Common question
**"I expected TDS but it didn't deduct."** Check three things: (1) the vendor ledger has TDS
applicable + a section + a rate; (2) the payment amount is **above** the section threshold;
(3) you're on a plan that includes TDS.

---

# tradeHQ — Getting started

Setting up tradeHQ takes a minute. On first launch a short setup wizard walks
you through it; you can also do it any time from the **Accounts** page.

1. **Add the person** who owns the account (a family member). Every account
   belongs to a person — that's how tradeHQ groups the family view.
2. **Add a broker account.** Pick the broker, give it a name, and enter the
   login it needs to pull: your broker **Login/Client ID, password, and TOTP
   (authenticator) secret**. These are encrypted on your PC and never leave it.
3. **Pull.** Go to **Pull / Sync**, tick the account(s) and click *Pull
   selected* — tradeHQ logs in, fetches your holdings, trades and ledger, and
   the **Dashboard** fills in.

You can add several people and accounts, and pull many at once from Pull / Sync.

**Where do I find my TOTP secret?** It's the authenticator key your broker
shows when you set up two-factor login (the long code behind the QR, sometimes
called the "manual entry key"). tradeHQ uses it to generate the 6-digit code at
pull time, so logins are automatic.

---

# tradeHQ — Overview

tradeHQ is a **trading & investment consolidation cockpit** for Windows. It
pulls reports from a family's many broker accounts and shows one consolidated
view: total wealth, cash position, realized profit/loss, ROI by trade type,
asset allocation, and profit over time (by day, week or month).

Who it's for: families and individuals who hold accounts across **several
brokers** and want one combined picture instead of logging into each broker
separately.

Key points:
- **Multi-broker:** consolidates holdings, P&L and ledger/cash flow across all
  your accounts, grouped by family member.
- **Auto-pull:** tradeHQ logs in to each broker for you (using your saved login
  and an authenticator/TOTP code it generates) and fetches the latest data —
  no manual downloads. Zerodha is supported today; more brokers are added over
  time.
- **Private & local:** your data and broker logins stay encrypted **on your own
  PC** (Windows DPAPI) and are never uploaded.
- **Bridges to Accounts HQ:** cash flow and holdings can flow to your Accounts
  HQ books for reconciliation.

tradeHQ records and consolidates your trading data — it is **not** a tax-filing
or compliance engine. For tax questions, check with your CA.

---

# tradeHQ — Plans & pricing

tradeHQ has a simple two-tier model:

- **Free** — 1 broker account, manual pull, the dashboard and holdings view,
  1 family member. Good for trying it out.
- **Standard — Rs. 200 / month** — all brokers with **auto-pull** (TOTP login),
  the full family wealth view, asset-allocation, the AI news screener, the
  Accounts HQ cash-flow bridge, and up to 6 family members.

It runs on Windows, and your data stays on your own computer. Prices are in INR.
For the latest plan details, see the tradeHQ page on the website or ask us at
info@ai-consultants.in.

---

# tradeHQ — Troubleshooting

**A pull failed.** Common causes:
- **Login details wrong or changed.** Re-check the account's Login/Client ID,
  password and TOTP secret on the Accounts page. If you recently changed your
  broker password, update it here too.
- **No login saved.** An account with no saved login can't be pulled — it shows
  greyed-out on Pull / Sync. Add the login on the Accounts page first.
- **Broker changed their login page.** The auto-login replays the broker's own
  website, so a broker redesign can temporarily break it until tradeHQ is
  updated. Check for an app update under **About → Check for updates**.

**The dashboard figures look stale.** Do a fresh pull from Pull / Sync, then
open the Dashboard — it re-reads after every pull.

**The top wealth number doesn't change when I switch the period.** That's by
design: total wealth is an *as-of-now* figure (free cash + holdings value), so
it doesn't move with the period. The gain/return shown next to it *does* follow
the period.

**The "Profit by day/week/month" chart is empty.** That account hasn't pulled a
realized-P&L (Console) report yet — pull again, or it may have no closed trades
in the selected period.

Still stuck? Use the in-app **Feedback** page or write to info@ai-consultants.in.

---

# Troubleshooting & common questions

## "It's asking for my licence key again after I updated."
Your data is safe — books live in `…\AppData\Local\Aiccounting\` and aren't touched by an
update. Re-open **License & Plan** and paste your key. If it keeps dropping, contact
`info@ai-consultants.in` with your key. *(Known issue under investigation.)*

## "My voucher won't post."
The most common reasons:
- **Dr ≠ Cr** — the debits and credits must balance. Check the live totals on the form.
- **Locked period** — the voucher date is inside a locked range (see Period Locks).
- A required ledger/amount is missing.

## "GST split as CGST/SGST but it was an inter-state sale (or vice-versa)."
GST is decided by **state codes**: same state → CGST+SGST, different state → IGST. Make sure
**your company state code** and the **party ledger's state code** are both correct. A party
with no state code is treated as intra-state. Fix the ledger's state code and re-post.

## "I expected TDS to be deducted but it wasn't."
Check: (1) the vendor ledger has **TDS applicable + section + rate**; (2) the payment is
**above** that section's threshold; (3) your plan includes TDS. See *TDS*.

## "I can't edit this voucher."
It's probably **reconciled** (matched in bank/ledger reconciliation) and therefore protected,
or its date is in a **locked period**. Undo the reconciliation match, or unlock the period,
then edit.

## "The AI Document Inbox shows an error."
Almost always the **AI key**: it's missing, wrong, expired, or out of credit. AI features are
"bring your own key" — set/replace it in **Settings → AI key**. AI features also need a Pro/
Premium plan.

## "A report looks out of date."
Reports read posted vouchers live — click **Refresh** after posting or fixing an entry.

## "Where is my data / how do I move to another PC?"
Each company is one file: `…\AppData\Local\Aiccounting\data\companies\<company>.db`. Back it
up (Backup & Restore), copy the backup to the new PC, install Accounts HQ there, and restore/
open it. Your data never leaves your machine unless you move it.

## "Can Accounts HQ file my GST/TDS returns?"
No. It **prepares** the figures and exports them for the portal; you or your CA file. It
records and computes — it isn't a filing/compliance engine and doesn't give tax advice.

## Still stuck?
Email **info@ai-consultants.in** with what you were doing and any error text.'''
