"""
Prepare a deploy bundle for the marketing site, with rollback safety.

What this does (no upload — local-only):
  1. Fetches the 8 current live pages from apps.ai-consultants.in and
     saves them under  marketing/_deploy/rollback/  (raw HTML).
     These are the violet/Stripe-coloured pages currently live.
  2. Copies the 8 local (teal, unified) pages to
     marketing/_deploy/upload/  ready for upload.
  3. Writes README_DEPLOY.md with step-by-step Hostinger instructions
     and the one-line rollback recipe.

Run this AFTER you have finished local edits and want to ship.
Re-running it overwrites _deploy/rollback/ with the latest live
snapshot — so don't re-run after you've already uploaded the new
pages, or you'll overwrite the rollback with the new copies.
"""
from __future__ import annotations
import shutil
import sys
import urllib.request
from pathlib import Path

LIVE_BASE = "https://apps.ai-consultants.in"

MARKETING = Path(__file__).resolve().parent
DEPLOY    = MARKETING / "_deploy"
ROLLBACK  = DEPLOY / "rollback"
UPLOAD    = DEPLOY / "upload"

PAGES = [
    "index.html",
    "pricing.html",
    "checkout.html",
    "contact.html",
    "privacy.html",
    "refund.html",
    "shipping.html",
    "terms.html",
]


def fetch_live(page: str, out: Path) -> tuple[bool, str]:
    url = f"{LIVE_BASE}/{page}"
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "deploy-prep/1.0 (rollback snapshot)"},
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read()
        out.write_bytes(body)
        return True, f"OK  {len(body):>7} bytes"
    except Exception as e:
        return False, f"FAIL  {type(e).__name__}: {e}"


def stage_local(page: str, out: Path) -> tuple[bool, str]:
    src = MARKETING / page
    if not src.exists():
        return False, f"MISSING local file: {src}"
    shutil.copy2(src, out)
    return True, f"OK  {src.stat().st_size:>7} bytes"


def main():
    ROLLBACK.mkdir(parents=True, exist_ok=True)
    UPLOAD.mkdir(parents=True, exist_ok=True)

    print(f"Rollback fetch from {LIVE_BASE}/ ...")
    print("-" * 60)
    rollback_ok = 0
    for page in PAGES:
        ok, msg = fetch_live(page, ROLLBACK / page)
        marker = "  " if ok else "!!"
        print(f"  {marker} {page:18}  {msg}")
        if ok:
            rollback_ok += 1
    print(f"  -> {rollback_ok}/{len(PAGES)} rollback files saved")
    print()

    print("Stage local (teal) -> upload bundle ...")
    print("-" * 60)
    upload_ok = 0
    for page in PAGES:
        ok, msg = stage_local(page, UPLOAD / page)
        marker = "  " if ok else "!!"
        print(f"  {marker} {page:18}  {msg}")
        if ok:
            upload_ok += 1
    print(f"  -> {upload_ok}/{len(PAGES)} upload files staged")
    print()

    readme = DEPLOY / "README_DEPLOY.md"
    readme.write_text(_readme_text(rollback_ok, upload_ok), encoding="utf-8")
    print(f"Wrote {readme}")
    print()
    print("Done. Open marketing/_deploy/README_DEPLOY.md for upload + rollback steps.")
    return 0 if (rollback_ok == upload_ok == len(PAGES)) else 1


def _readme_text(rollback_ok: int, upload_ok: int) -> str:
    return f"""# Marketing site deploy — apps.ai-consultants.in

Generated by `_deploy_prepare.py`.

- **rollback/** — snapshot of the 8 pages currently live ({rollback_ok}/8 fetched). Keep this folder; it's your one-click revert.
- **upload/**   — the 8 new pages ready to upload ({upload_ok}/8 staged).

## To deploy (new teal pages)

1. Log in to Hostinger -> Websites -> apps.ai-consultants.in -> File Manager.
2. Navigate to `public_html/` (or wherever the site root maps to).
3. Upload all 8 files from `_deploy/upload/` over the existing ones. Choose **Overwrite** when prompted.
4. Hard-refresh in browser (Ctrl-Shift-R) to confirm:
   - Accent colour is teal (#0EA5A5), not violet.
   - Pricing page shows AHQ tiers from xlsx (20,000 / 50,000 / 100,000 txn).
   - Checkout has 3-product toggle including tradeHQ.

## To roll back (restore the violet pages)

1. Same File Manager + `public_html/`.
2. Upload all 8 files from `_deploy/rollback/` over the live ones. **Overwrite.**
3. Hard-refresh.

That's it — same operation, different folder.

## Notes

- `_deploy/rollback/` was captured at the moment this script ran. **Do not re-run `_deploy_prepare.py` after you've uploaded the new pages** — that would overwrite the rollback with the new files and you'd lose the revert option.
- The 8 pages above are the full marketing site at apps.ai-consultants.in (root). The RWA HQ React SPA at `apps.ai-consultants.in/rwahq/` is a separate bundle and is NOT touched here.
- Files are byte-identical to what's on the server / what's in `marketing/`. No path rewrites.
"""


if __name__ == "__main__":
    sys.exit(main())
